### ISSUE TITLE
It shows endless "Loading...".

### ISSUE THREAD

**Issue by iPAS** [microBlock-IDE/microBlock-IDE-offline#1]
It shown:

```
npm start

> microblock-ide-offline@2.3.0 start
> electron .

(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

```

Then, never finish the loading operation.

**Comment by maxpromer** [comment]
> It shown:
> 
> ```
> npm start
> 
> > microblock-ide-offline@2.3.0 start
> > electron .
> 
> (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
> ```
> 
> Then, never finish the loading operation.

Thank you so much for report. I will check.

**Comment by iPAS** [comment]
FYI. This is my npm environment:

microblock-ide-offline@2.3.0
│ ~/microBlock-IDE-offline
│ microBlock IDE (offline version)
├── bcrypt@5.0.0
│   
├── dive@0.5.0
│   
├── electron-builder@22.9.1
│   
├── electron-rebuild@2.0.2
│   
├── electron@9.4.4
│   
└── serialport@9.0.1

**Comment by iPAS** [comment]
Hi @maxpromer,
Eventually, I have found the solution -- and it work!
It is mentioned in https://serialport.io/docs/guide-installation/.
I had to run
`> npm install --save-dev electron-rebuild`
instead of 
`> npm install`.
Probably, it should be suggested in README.md.

**Comment by maxpromer** [comment]
Thank you so much. I add `npm install --save-dev electron-rebuild` to README.md
